# Generated by Django 5.2.16 on 2026-07-26 12:34

import apps.inventory.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.CharField(default=apps.inventory.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('subCategoryName', models.TextField()),
                ('subCategoryAbbreviation', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
                ('lastItemSerialNumber', models.IntegerField(default=0)),
                ('subCategoryNameNormalized', models.TextField(blank=True, null=True)),
                ('subCategoryAbbreviationNormalized', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='inventory.category')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subcategories',
            },
        ),
    ]
