# Generated by Django 5.2.16 on 2026-07-26 12:38

import apps.inventory.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(default=apps.inventory.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('roomName', models.TextField()),
                ('allottedTo', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
                ('roomNameNormalized', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='inventory.floor')),
                ('roomType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='inventory.roomtype')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
