# Generated by Django 5.2.16 on 2026-07-26 12:41

import apps.inventory.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(default=apps.inventory.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('itemName', models.TextField()),
                ('itemModelNumberOrMake', models.TextField(blank=True, null=True)),
                ('itemAcquiredDate', models.DateField()),
                ('itemCost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('itemStatus', models.TextField(choices=[('Working', 'Working'), ('Repairable', 'Repairable'), ('Not working', 'Not working')])),
                ('itemSource', models.TextField(choices=[('Purchase', 'Purchase'), ('Donation', 'Donation')])),
                ('itemDescription', models.TextField(blank=True, null=True)),
                ('itemSerialNumber', models.TextField(default='0')),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
                ('deactivatedAt', models.DateTimeField(blank=True, null=True)),
                ('itemRemark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to=settings.AUTH_USER_MODEL)),
                ('itemCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category')),
                ('itemFloor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.floor')),
                ('itemRoom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.room')),
                ('itemSubCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.subcategory')),
            ],
            options={
                'db_table': 'items',
                'indexes': [models.Index(fields=['-updated_at'], name='items_updated_109f6f_idx')],
            },
        ),
    ]
