# Generated by Django 5.2.16 on 2026-07-26 12:43

import apps.inventory.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.CharField(default=apps.inventory.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('entityType', models.TextField(choices=[('Item', 'Item'), ('User', 'User'), ('Room', 'Room'), ('Category', 'Category'), ('Floor', 'Floor'), ('Roomtype', 'Roomtype'), ('SubCategory', 'SubCategory')])),
                ('entityId', models.CharField(blank=True, max_length=24, null=True)),
                ('entityName', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('performedByName', models.TextField(blank=True, null=True)),
                ('performedByRole', models.TextField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activitylogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
