# Generated by Django 5.2.16 on 2026-07-31 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemSubCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.subcategory'),
        ),
    ]
