# Generated by Django 5.2.16 on 2026-07-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_item_itemcategory_alter_item_itemsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomNo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
