# Generated by Django 5.2.16 on 2026-08-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item_search_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
