# Generated by Django 5.2.16 on 2026-08-12

import apps.inventory.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_item_itemcost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.CharField(default=apps.inventory.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ("departmentName", models.TextField()),
                ("isActive", models.BooleanField(db_column="isActive", default=True)),
                ("departmentNameNormalized", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("createdBy", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="departments", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "departments"},
        ),
        migrations.AddField(
            model_name="floor",
            name="department",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="floors", to="inventory.department"),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="department",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="room_types", to="inventory.department"),
        ),
    ]
