# Generated by Django 5.2.16 on 2026-08-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_department_floor_department_roomtype_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='entityType',
            field=models.TextField(choices=[('Item', 'Item'), ('User', 'User'), ('Room', 'Room'), ('Category', 'Category'), ('Floor', 'Floor'), ('Department', 'Department'), ('Roomtype', 'Roomtype'), ('SubCategory', 'SubCategory')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemAcquiredDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
