# Generated by Django 5.2.16 on 2026-08-12 02:52

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_consecutive_lockouts_user_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('fullName', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('department', models.TextField()),
                ('rollNo', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'access_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
