# Generated by Django 5.2.16 on 2026-08-12 16:51

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accessrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedRequester',
            fields=[
                ('id', models.CharField(default=apps.accounts.models.generate_object_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_requesters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocked_requesters',
                'ordering': ['-created_at'],
            },
        ),
    ]
