# Generated by Django 5.2.16 on 2026-08-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_blockedrequester"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlockedRequester",
        ),
        migrations.DeleteModel(
            name="AccessRequest",
        ),
    ]
